apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novu-worker
  template:
    metadata:
      labels:
        app: novu-worker
    spec:
      containers:
        - name: novu-worker
          image: ghcr.io/novuhq/novu/worker:3.15.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: DISABLE_TELEMETRY
              value: "true"
            - name: MONGO_URL
              value: "mongodb://novu:novu123@mongodb.dev.svc.cluster.local:27017/novu"
            - name: REDIS_URL
              value: "redis://:NovuRedis2024@redis-master.dev.svc.cluster.local:6379"
            - name: REDIS_HOST
              value: "redis-master.dev.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "NovuRedis2024"
            - name: REDIS_CACHE_SERVICE_HOST
              value: "redis-master.dev.svc.cluster.local"
            - name: REDIS_CACHE_SERVICE_PORT
              value: "6379"
            - name: JWT_SECRET 
              value: "n0vuJ@tS3cr3tK3y!L0c@lD3v#2024$"
            - name: STORE_ENCRYPTION_KEY
              value: "nv0uEncryptK3y!@#$Dev2024%^&*Loc"
            - name: API_ROOT_URL
              value: "http://novu-api.dev.svc.cluster.local:3000"
            - name: BROKER_TYPE
              value: "REDIS"
            - name: LOGGING_LEVEL
              value: "info"
            - name: STORAGE_SERVICE
              value: "LOCAL"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=768"