apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-ws
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novu-ws
  template:
    metadata:
      labels:
        app: novu-ws
    spec:
      containers:
        - name: novu-ws
          image: ghcr.io/novuhq/novu/ws:3.15.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: DISABLE_TELEMETRY
              value: "true"
            - name: MONGO_URL
              value: "mongodb://novu:novu123@mongodb.dev.svc.cluster.local:27017/novu"
            - name: REDIS_URL
              value: "redis://:NovuRedis2024@redis-master.dev.svc.cluster.local:6379"
            - name: REDIS_HOST
              value: "redis-master.dev.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "NovuRedis2024"
            - name: JWT_SECRET
              value: "n0vuJ@tS3cr3tK3y!L0c@lD3v#2024$"
            - name: STORE_ENCRYPTION_KEY
              value: "nv0uEncryptK3y!@#$Dev2024%^&*Loc"
            - name: WS_URL
              value: "http://localhost:3002"
            - name: API_ROOT_URL
              value: "http://novu-api.dev.svc.cluster.local:3000" 
            - name: FRONT_BASE_URL
              value: "http://localhost:4000"
            - name: NEW_RELIC_ENABLED
              value: "false"
            - name: NEW_RELIC_APP_NAME
              value: "novu-ws"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=384"