apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: dev
  labels:
    app: django
  annotations:
    "kubernetes.io/change-cause": "Initial State"
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: django 
  template:
    metadata:
      labels:
        app: django 
    spec:
      containers:
      - name: django-container
        image: duvindune/backend:v4
        ports:
          - containerPort: 8000

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"